openapi: 3.0.0
info:
  title: RecipeHub API
  version: 1.0.0
  description: Сервис для обмена рецептами и кулинарных блогов

servers:
  - url: http://localhost:3000/api
    description: API-сервер

paths:
  /auth/register:
    post:
      tags: ["Auth"]
      summary: Регистрация нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        "201":
          description: Пользователь создан

  /auth/login:
    post:
      tags: ["Auth"]
      summary: Авторизация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: Получение JWT-токена

components:
  schemas:
    RegisterRequest:
      type: object
      required: [username, firstName, lastName, password]
      properties:
        username:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        about:
          type: string
    
    LoginRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
        password:
          type: string
